<?
switch ($room_go)
{
	case 'castle':		$room_go = "Бойцовский Клуб";
	break;
	case 'km_1':		$room_go = "Зал воинов";
	break;
	case 'km_2':		$room_go = "Зал воинов 2";
	break;
	case 'km_3':		$room_go = "Зал воинов 3";
	break;
	case 'km_4':		$room_go = "Будуар";
	break;
	case 'km_5':		$room_go = "Комната Знахаря";
	break;
	case 'km_6':		$room_go = "Рыцарский Зал";
	break;
	case 'km_7':		$room_go = "Торговый Зал";
	break;
	case 'km_8':		$room_go = "Зал закона";
	break;
	case 'castle2':		$room_go = "Этаж 2";
	break;
	case 'centplosh':	$room_go = "Центральная Площадь";
	break;
	case 'fairstreet':	$room_go = "Страшилкина улица";
	break;
	case 'brak':		$room_go = "Храм";
	break;
	case 'comok':		$room_go = "Комиссионка";
	break;
	case 'bank':		$room_go = "Банк";
	break;
	case 'stella':		$room_go = "Стела Выбора";
	break;
	case 'prision':		$room_go = "Тюрьма";
	break;
	case 'shop':		$room_go = "Магазин";
	break;
	case 'registratura':$room_go = "Регистратура кланов";
	break;
	case 'rep':			$room_go = "Ремонтная мастерская";
	break; 
	case 'cityhall':	$room_go = "Академия";
	break;
	case 'zarabotok':	$room_go = "работа";
	break;
	case 'kuzna':		$room_go = "Завод";
	break;
	case 'river':		$room_go = "Пруд";
	break;
	case 'casino':		$room_go = "Казино";
	break;
	case 'casino1':		$room_go = "Блек джек холл";
	break;
	case 'lotto':		$room_go = "Лотерея";
	break;
	case 'kosti':		$room_go = "Кости";
	break;
	case '10x5':		$room_go = "Подвал";
	break;
	case 'mail':		$room_go = "Почтовое отделение";
	break;
	case 'sell':		$room_go = "Скупочный магазин";
	break;
	case 'cell':		$room_go = "Лес";
	break;
	case 'catle':		$room_go = "Хибара скотовода";
	break;
	case 'znahar':		$room_go = "Палатка знахаря";
	break;
	case 'lesorub':		$room_go = "Домик лесоруба";
	break;
	case 'go_for':		$room_go = "Темный Лес";
	break;
	case 'dub':			$room_go = "Дубовая роща";
	break;
	case 'bereza':		$room_go = "Березовая роща";
	break;
	case 'arena':		$room_go = "Арена";
	break;
	case 'forespath':	$room_go = "Дорога на лес";
	break;
	case 'mountownpath':$room_go = "Дорога на Mountown";
	break;
}
?>